### ISSUE TITLE
Monitor usage resulting in repeated printing

### ISSUE THREAD

**Issue by csheaff** [CFMTech/pytest-monitor#26]
**Describe the bug**
I use captured print statements to build test reports. In using pytest-monitor, I notice that its usage produces the effect of repeating these statements. 

**To Reproduce**
1. Create a simple hello-world pytest function.
2. Run the test with the `-s` flag to allow printing to console, observe multiple statements.
3. Run again but include `-p no:monitor`, observe single statement.

**Expected behavior**
The printing of a single statement.

**Screenshots**
![image](https://user-images.githubusercontent.com/10719781/95602259-46e87900-0a1a-11eb-9427-07b1f3e709a7.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04LTS
 - Python 3.7.8
 - Pytest 6.0.2
 - Other plugins:  metadata, html

**Comment by js-dieu** [comment]
Hello @csheaff 

Thanks for reporting. It is a bit weird to me as I do not play at all with capture fixtures nor the way pytest handles logs and prints. 
I might be hard to analyze and debug but I'll try to have a look this week prior to the upcoming release of pytest-monitor.

**Comment by tobni** [comment]
Ill just add that it is not only printing that is repeated, the test function is executed multiple times. This can cause test-failure, if for example the tests are using in memory storage.

using `pytest 6.1`, `pytest-monitor 1.4`.

**Comment by js-dieu** [comment]
Hi @tobni 

This is critical indeed. AFAIK, *pytest-monitor* is not showing up such behavior with previous versions of pytest. I did run it with a set of 7000+ tests and the ELA time remains constant. I'll need to get some time to dive deep into this issue. 
May I suggest for now to use pytest 5.X series? Or is this something you can't consider for any reason?

**Comment by tobni** [comment]
Downgrading works for my own testing of parts of a test suite, but is not an option for CI etc, where I was hoping `pytest-monitor` would grant real insight/value.

**Comment by js-dieu** [comment]
I understand. I'll prioritize the investigation.

**Comment by js-dieu** [comment]
After some investigations, I think the problem is related to *memory_profiler*.
The following example illustrates the problem you are experiencing:
```python
import memory_profiler

def foo():
   print('Hello World')

if __name__ == '__main__':
   print(memory_profiler.memory_usage((foo, ()), max_usage=True, retval=True))
```

This prints the following on my machine:
```
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
(25.5625, None)
```

If I remove the memory profiling part from the plugin, the output is as expected. I'll ask for some support to memory_profiler.

**Comment by js-dieu** [comment]
Hello @csheaff , @tobni 

I might have found a workaround. **memory_profiler** collects datas from a dedicated process. For fast enough functions, it repeats the process until (in our case) 4 measures have been done.

I have constrained the collect to perform 1 iteration only but I have no clue regarding eventual impacts on the collected measures.

I will need to compare with previous run on some repos. I'll check that this week.
