### ISSUE TITLE
Crash on __init__ if psutil.cpu_freq() gives no results

### ISSUE THREAD

**Issue by MattiasMartens** [CFMTech/pytest-monitor#56]
**Describe the bug**
When running on a system whose architecture is such that `psutil.cpu_freq()` returns `None`, `pytest-monitor` crashes `pytest` on startup:

```
AttributeError: 'NoneType' object has no attribute 'current'
```

**To Reproduce**

An example of an architecture with this problem is `5.10.104-linuxkit`, the version used by the Docker image `python:3.9-slim-buster`.

As of the current version 5.9.0, `psutil` tries to find the CPU service in `/sys/devices/system/cpu/cpufreq/policy0` or `/sys/devices/system/cpu/cpu0/cpufreq`; if it can't find it there, it checks `/proc/cpuinfo` for lines starting with `cpu mhz`. But that doesn't always work (in my case the CPU was given only in BogoMIPS). In that case it returns `None`, triggering this crash.

**Expected behavior**

Prefer that `pytest-monitor` fails gracefully in this case, or perhaps defaults CPU utilization to zero and emits a warning.

**Desktop (please complete the following information):**
 - OS: 5.10.104-linuxkit
 - Python version: 3.9.12
 - Pytest version: 6.2.1
 - pytest-monitor version: 1.6.3

**Comment by js-dieu** [comment]
Hello @MattiasMartens 

Thanks for reporting. I'll strive to make a quickfix for that this week.

Keep you posted
